version: '3'

services:
  web:
    image: web_image
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - ./media:/app/map/media
    ports:
      - "8000:8000"
      