# Generated by Django 4.2 on 2023-04-13 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.RenameField(
            model_name='floor',
            old_name='image',
            new_name='map_image',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
        migrations.AddField(
            model_name='user',
            name='song',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
