# Generated by Django 4.2 on 2023-04-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profileview_user_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='place',
        ),
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
