# Generated by Django 4.2 on 2023-04-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileview',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
