# Generated by Django 4.2 on 2023-04-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profileview_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileview',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='profileview',
            name='target_user',
        ),
        migrations.AddField(
            model_name='profileview',
            name='from_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='from_user', to='core.user'),
        ),
        migrations.AddField(
            model_name='profileview',
            name='target_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='target_user', to='core.user'),
        ),
    ]
