# Generated by Django 4.2 on 2023-04-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_profileview_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileview',
            name='from_user',
            field=models.ManyToManyField(blank=True, related_name='from_user', to='core.user'),
        ),
        migrations.AlterField(
            model_name='profileview',
            name='target_user',
            field=models.ManyToManyField(blank=True, related_name='target_user', to='core.user'),
        ),
    ]
