# Generated by Django 4.2 on 2023-04-14 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profileview_from_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileview',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='profileview',
            name='target_user',
        ),
        migrations.AddField(
            model_name='profileview',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='core.user'),
        ),
        migrations.AddField(
            model_name='profileview',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to='core.user'),
        ),
    ]
