# Generated by Django 4.2 on 2023-04-14 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_profileview_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_time_set_location',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0)),
        ),
    ]
