# Generated by Django 4.2 on 2023-05-18 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_song_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True)),
                ('tg_username', models.CharField(max_length=1000, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('who_invited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_invited_visitor', to='core.visitor')),
            ],
        ),
    ]
